### PR TITLE
Missing options props

### PR DESCRIPTION
**Pull request by Freddy03h**
Add and removing props and options regarding react-navigation v5 documentation.

### CODE REVIEW

**Comment by Freddy03h** [comment]
I tried those changes on my own project this week-end, it work well :)

- fix tabBar : function that return an element instead of being a component (my previous PR about it was a bit rushed ^^' )
- add the view `MaterialTopTabBar` in MaterialTopTabs
- add and remove many props and options on MaterialTopTabs, BottomTabs and Stack

For the `peerDependencies` I think we should add all the dependencies? But at least remove `/core` because it's now recommended to not add it (only add `/native`). Should I replace it with native only or should I add all other dep ? (stack, tabs, drawer, etc)

**Comment by Freddy03h** [comment]
I didn't tried all the new props/options, but I'm pretty confident about the ones I removed from `MaterialTopTabs`

**Comment by MoOx** [comment]
For the peer deps yes, please do what is recommended, so only what user should have as deps :) And all of them. Worst case scenario is that you get a warning for a dep you don't use, that's acceptable for now

As soon as you do that, I will adjust the version according to this... Since we don't "match" a single dep, the version number will be different that what we do for other packages.

**Comment by Freddy03h** [comment]
Updated peerDependencies to this:
```
  "peerDependencies": {
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/material-top-tabs": "^5.0.0",
    "@react-navigation/material-bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.0.0",
```
Regarding all packages changelog, it almost bugfixes, and features are almost typescript definitions and listeners things. There is a somes features linked to a specific minor version of a packaged but we don't supported them yet. So I think it's better to keep the 5.0.0 for the minimum version.

**Comment by MoOx** [comment]
Your PR is still in Draft, do you have other things to push or is it ready as it is?

**Comment by Freddy03h** [comment]
Nothing else to push for now ^^

**Comment by idkjs** [comment]
@Freddy03h is this ready to go?

**Comment by Freddy03h** [comment]
Thank you!

**Pull request merged**
