### PR TITLE
Add none header option

### PR DESCRIPTION
**Pull request by DCKT**
Hello,

The `header` option can be `null` following the documentation, so I added an external

Cheers

### CODE REVIEW

**Comment by cknitt** [comment]
Thanks again! Something is weird here though, Github shows me the changes from the previously merged two PRs (reset, headerShown) in this PR, too?

**Comment by DCKT** [comment]
Indeed, I made this upon these other changes because I needed it (did It
too fast)


Le 15 novembre 2019 à 16:52:12, Christoph Knittel (notifications@github.com)
a écrit:

Thanks again! Something is weird here though, Github shows me the changes
from the previously merged two PRs (reset, headerShown) in this PR, too?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/reason-react-native/reason-react-navigation/pull/17?email_source=notifications&email_token=AAL2BBM5FTOIPVGUVWFSRODQT3ASZA5CNFSM4JMCDME2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEF3D4A#issuecomment-554414576>,
or unsubscribe

**Comment by cknitt** [comment]
Yes, that's totally fine, but the two others are already merged, so I would have expected to see only one change when comparing against the current master.

**Comment by cknitt** [comment]
I'll try to merge and see what happens.

**Comment by cknitt** [comment]
Ok, it's fine, when merged I see just the one change in the commit.

**Pull request merged**
